global PLAYER_X, PLAYER_Y, MOVE_SPEED, PLAYER_DIRECTION, LAST_DIRECTION, PLAYER_ANGLE
global BULLETS, BULLET_SPEED, BULLET_LIFETIME, SHOOT_COOLDOWN, LAST_SHOT_TIME

# Player's
PLAYER_X = 400.0
PLAYER_Y = 300.0
MOVE_SPEED = 7.0
PLAYER_DIRECTION = [0.0, 0.0]
LAST_DIRECTION = [0.0, 0.0]
PLAYER_ANGLE = 0.0

# Bullet's:
BULLETS = []
BULLET_SPEED = 4.5
BULLET_SPEED_FAST = BULLET_SPEED * 2
BULLET_LIFETIME = 3000
SHOOT_COOLDOWN = 200
LAST_SHOT_TIME = 0

player_x = PLAYER_X
player_y = PLAYER_Y
move_speed = MOVE_SPEED
player_direction = PLAYER_DIRECTION
last_direction = LAST_DIRECTION
player_angle = PLAYER_ANGLE
bullets = BULLETS
bullet_speed = BULLET_SPEED
bullet_lifetime = BULLET_LIFETIME
shoot_cooldown = SHOOT_COOLDOWN
last_shot_time = LAST_SHOT_TIME